[programs.obsidian]
description = "Obsidian notes"
depends-on = ["flathub-remote"]

[programs.obsidian.version]
command = "flatpak --user info md.obsidian.Obsidian"
regex = "Version: ([0-9][0-9.]*)"

[programs.obsidian.install]
flatpak = "flatpak --user install -y flathub md.obsidian.Obsidian"
