# Shared truth for every macOS machine.
base = true

scripts = [
  "dotfiles-bootstrap",
  "dotfiles-pull",
  "dotfiles-apply",
  "dotfiles-ssh-remote",
  "asdf-tools",
  "asdf-default-packages",
  "setup-git",
  "download-fonts",
  "setup-completions",
]

[pm]
awscli = "brew"
fzf = "brew"
scrcpy = "brew"
atuin = "brew"
bat = "brew"
btop = "brew"
chezmoi = "brew"
fd = "brew"
git-delta = "brew"
lazydocker = "brew"
lazygit = "brew"
ripgrep = "brew"
starship = "brew"
tmux = "brew"
workmux = "brew"
trash-cli = "brew"
tree-sitter-cli = "brew"
yazi = "brew"
yq = "brew"
zoxide = "brew"
tpack = "brew-cask"
opencode = "brew"
asdf = "script"
ngrok = "script"
raycast = "brew-cask"
