# The linux cask lives in the ublue-os tap (see ublue-os-tap.toml).
[programs.jetbrains-toolbox]
description = "JetBrains Toolbox"
depends-on = ["ublue-os-tap"]

[programs.jetbrains-toolbox.install.brew-linux]
installer = "brew-cask"
pkg = "jetbrains-toolbox-linux"

[programs.jetbrains-toolbox.install.brew-macos]
installer = "brew-cask"
