scripts = [
  "solaar-no-autostart",
  "remove-firefox-flatpak",
  "chezmoi-init",
  "asdf-tools",
  "chezmoi-dotfiles-remote",
  "setup-ssh fedora",
  "setup-git",
  "download-fonts",
  "setup-completions",
  "link-jetbrains-launchers-linux",
  "remove-shadowed-rpms",
  "setup-libvirt",
]

[pm]
setup-dnf = "dnf"
vlc = "dnf"
okular = "dnf"
solaar = "dnf"
konsole = "dnf"
dbus-devel = "dnf"
dnf-plugins-core = "dnf"
zlib-devel = "dnf"
bzip2-devel = "dnf"
readline-devel = "dnf"
sqlite = "dnf"
sqlite-devel = "dnf"
openssl-devel = "dnf"
xz-devel = "dnf"
libffi-devel = "dnf"
findutils = "dnf"
tk-devel = "dnf"
libzstd-devel = "dnf"
autoconf = "dnf"
gcc = "dnf"
rust = "dnf"
patch = "dnf"
libyaml-devel = "dnf"
gdbm-devel = "dnf"
ncurses-devel = "dnf"
perl-FindBin = "dnf"
development-tools-group = "dnf"
virtualization = "dnf"
kitty = "dnf"
code = "dnf"
antigravity = "dnf"
firefox = "dnf"
1password = "dnf"
google-chrome-stable = "dnf"
slack = "dnf"
anydesk = "dnf"
teams-for-linux = "dnf"
sublime-text = "dnf"
yq = "brew"
atuin = "brew"
btop = "brew"
bat = "brew"
ripgrep = "brew"
zoxide = "brew"
chezmoi = "brew"
fd = "brew"
trash-cli = "brew"
tree-sitter-cli = "brew"
tmux = "brew"
git-delta = "brew"
lazygit = "brew"
lazydocker = "brew"
starship = "brew"
yazi = "brew"
tpack = "brew-cask"
opencode = "brew"
jetbrains-toolbox = "brew-linux"
ublue-os-tap = "brew"
flathub-remote = "flatpak"
obsidian = "flatpak"
asdf = "script"
ngrok = "script"
jumpkwapp = "script"
just = "dnf"
vim-enhanced = "dnf"
curl = "dnf"
git = "dnf"
procps-ng = "dnf"
libxcrypt-compat = "dnf"
zsh = "dnf"
google-cloud-cli = "dnf"
