[pm]
vlc = "dnf"
okular = "dnf"
solaar = "dnf"
konsole = "dnf"
dbus-devel = "dnf"
dnf-plugins-core = "dnf"
zlib-devel = "dnf"
bzip2-devel = "dnf"
readline-devel = "dnf"
sqlite = "dnf"
sqlite-devel = "dnf"
openssl-devel = "dnf"
xz-devel = "dnf"
libffi-devel = "dnf"
findutils = "dnf"
tk-devel = "dnf"
libzstd-devel = "dnf"
autoconf = "dnf"
gcc = "dnf"
rust = "dnf"
patch = "dnf"
libyaml-devel = "dnf"
gdbm-devel = "dnf"
ncurses-devel = "dnf"
perl-FindBin = "dnf"
development-tools-group = "dnf"
kitty = "dnf"
code = "dnf"
antigravity = "dnf"
firefox = "dnf"
1password = "dnf"
google-chrome-stable = "dnf"
